cookie:
  expiry_days: 30
  key: some_signature_key
  name: lt_cookie
credentials:
  usernames:
    controller:
      email: controller@gmail.com
      failed_login_attempts: 0
      id: 34e231f9-5e6e-46f3-8492-4e850312ff68
      logged_in: false
      name: controller
      password: $2b$12$pjf6rzNmiRDNh9YD4NuOp.Ig5KFapCX.eoWtd8qOPOSFLMt.H1Q2.
      role: user
    wilerfoz:
      email: wilerfoz@gmail.com
      failed_login_attempts: 0
      id: 4f172429-98d0-4e4e-b525-255810c80f62
      logged_in: true
      name: wilerson
      password: $2b$12$H.BWcaPP3izGt/My1S6cde9pp2e2efk4ittqWg4rl.wZ2QChog7uC
      role: admin
preauthorized:
  emails:
  - wilerfoz@gmail.com
